from aromatwin.routers import (
    admin_review,
    brands,
    bulk_profiles,
    catalogue,
    clone_matches,
    consumer_scent,
    enrichment_reviews,
    fragrances,
    health,
    launch_intelligence,
    maison,
    match_candidates,
    notes,
    operations,
    pilot_workflow,
    platform_completion,
    private_pilot,
    private_supplier_workflow,
    product_catalogue,
    profile_drafts,
    recommendations,
    review_workflow,
    scent_vectors,
    scentprint,
    search,
    seller_demand,
    supplier_offers,
    supplier_sourcing,
)

# Compatibility alias retained for imports written before the route was explicitly private.
supplier_items = private_supplier_workflow

ROUTERS = (
    health.router,
    admin_review.router,
    maison.router,
    product_catalogue.router,
    supplier_items.router,
    supplier_offers.router,
    supplier_sourcing.router,
    seller_demand.router,
    consumer_scent.router,
    launch_intelligence.router,
    pilot_workflow.router,
    private_pilot.router,
    operations.router,
    platform_completion.router,
    review_workflow.router,
    bulk_profiles.router,
    match_candidates.router,
    enrichment_reviews.router,
    catalogue.router,
    brands.router,
    fragrances.router,
    notes.router,
    profile_drafts.router,
    search.router,
    recommendations.router,
    scent_vectors.router,
    scentprint.router,
    clone_matches.router,
)
