from aromatwin.routers import (
    brands,
    catalogue,
    clone_matches,
    enrichment_reviews,
    fragrances,
    health,
    match_candidates,
    notes,
    profile_drafts,
    recommendations,
    scent_vectors,
    scentprint,
    search,
    supplier_items,
)

ROUTERS = (
    health.router,
    supplier_items.router,
    match_candidates.router,
    enrichment_reviews.router,
    catalogue.router,
    brands.router,
    fragrances.router,
    notes.router,
    profile_drafts.router,
    search.router,
    recommendations.router,
    scent_vectors.router,
    scentprint.router,
    clone_matches.router,
)
